set SERVEROUTPUT on;
BEGIN
    DBMS_OUTPUT.PUT_LINE('HOLA MUNDO');
END;
/
DECLARE HM VARCHAR2(100):= 'HOLA MUNDO';
BEGIN

    DBMS_OUTPUT.PUT_LINE(HM);
END;
/
DECLARE HM VARCHAR2(100):= 'HOLA MUNDO ';
        NUMERO INT:=32;
BEGIN

    DBMS_OUTPUT.PUT_LINE(HM||NUMERO);
END;
/
DECLARE
    MIFECHA DATE;
    MIFECHA2 DATE:= '23/01/2026';
    NONULA NUMBER(3,2) NOT NULL:=111;
    SALE NUMBER (4,2) := 10.99;
    CLASE VARCHAR2(15):= 'CLASE DE DAMDAW';
    CE CONSTANT INT:=11;
BEGIN

END;
/
DECLARE
    NOMBREEMPLEADO EMP.ENAME%TYPE := 'TOMAS';
    MIEMPLEADO EMP%ROWTYPE;
BEGIN
    MIEMPLEADO.ENAME := 'MARIA';
    DBMS_OUTPUT.PUT_LINE(NOMBREEMPLEADO);
    DBMS_OUTPUT.PUT_LINE(MIEMPLEADO.SAL);
    DBMS_OUTPUT.PUT_LINE(MIEMPLEADO.ENAME);
END;
/
DECLARE
MICLIENTE CLIENTES%ROWTYPE;
BEGIN
SELECT ID, NOMBRE, TFNO INTO MICLIENTE FROM CLIENTES WHERE NOMBRE ='ANDRES PEREZ';
DBMS_OUTPUT.PUT_LINE(MICLIENTE.ID);
DBMS_OUTPUT.PUT_LINE(MICLIENTE.NOMBRE);
DBMS_OUTPUT.PUT_LINE(MICLIENTE.TFNO);
END;
/
DECLARE
    NOMBRE EMP.ENAME%TYPE;
    EMPLEADO EMP%ROWTYPE;
BEGIN
    SELECT ENAME INTO NOMBRE FROM EMP WHERE EMPO=7839;
    SELECT * INTO EMPLEADO FROM EMP WHERE EMPO =7698;
    DBMS_OUTPUT.PUT_LINE(EMPLEADO.ENAME|| ' '||NOMBRE);
END;
/
DECLARE
NUMERO INT:=&METE_UN_NUMERO;
BEGIN
    DBMS_OUTPUT.PUT_LINE('SU NUMERO  '||NUMERO);
END;
/
UNDEFINE METE_UN_NUMERO;

DECLARE
BASE INT:=&METE_LA_BASE;
ALTURA INT:=&METE_LA_ALTURA;
AREA NUMBER(5,2):=ROUND(BASE*ALTURA/2);
BEGIN
    
    DBMS_OUTPUT.PUT_LINE('SU AREA ES: '|| AREA);
END;
/
UNDEFINE METE_LA_BASE;
UNDEFINE METE_LA_ALTURA;

DECLARE
NOMBRE VARCHAR2(10):= '&DIME_TU_NOMBRE';
APELLIDO VARCHAR2(10):= '&DIME_TU_APELLIDO';
BEGIN
    
    DBMS_OUTPUT.PUT_LINE('SU NOMBRE COMPLETO ES '|| NOMBRE|| ' ' ||APELLIDO);
END;
/
UNDEFINE DIME_TU_NOMBRE;
UNDEFINE DIME_TU_APELLIDO;

DECLARE
NUMERO1 INT:= &DIME_TU_PRIMER_NUMERO;
NUMERO2 INT:= &DIME_TU_SEGUNDO_NUMERO;
SUMA INT := NUMERO1+NUMERO2;
RESTA INT:=NUMERO1-NUMERO2;
MULTIPLICACION INT :=NUMERO1*NUMERO2;
DIVISION NUMBER(5,2):=NUMERO1/NUMERO2;
BEGIN
    
    DBMS_OUTPUT.PUT_LINE(' SU SUMA ES: '||SUMA|| ' SU RESTA ES: '|| RESTA|| ' SU MULTIPLICACION ES: '||MULTIPLICACION||' SU DIVISION ES: '||DIVISION);
END;
/
UNDEFINE DIME_TU_PRIMER_NUMERO;
UNDEFINE DIME_TU_SEGUNDO_NUMERO;

DECLARE
NUMERO1 INT:= &DIME_TU_PRIMER_NUMERO;
NUMERO2 INT:= &DIME_TU_SEGUNDO_NUMERO;
RESTA INT:=NUMERO1-NUMERO2;
BEGIN
IF NUMERO1 >= NUMERO2 THEN

    DBMS_OUTPUT.PUT_LINE( ' SU RESTA ES: '|| RESTA );
    ELSE
    DBMS_OUTPUT.PUT_LINE(NUMERO1 || ' ES MENOR QUE '|| NUMERO2);
    END IF;
END;
/
UNDEFINE DIME_TU_PRIMER_NUMERO;
UNDEFINE DIME_TU_SEGUNDO_NUMERO;

DECLARE
NUMERO1 INT:= &DIME_TU_PRIMER_NUMERO;
NUMERO2 INT:= &DIME_TU_SEGUNDO_NUMERO;
SUMA INT := NUMERO1+NUMERO2;
BEGIN
IF NUMERO1 > NUMERO2 THEN

    DBMS_OUTPUT.PUT_LINE( ' SU SUMA ES: '|| SUMA );
    ELSE
    DBMS_OUTPUT.PUT_LINE('SU NUMERO NO ES CORRECTO');
    END IF;
END;
/
UNDEFINE DIME_TU_PRIMER_NUMERO;
UNDEFINE DIME_TU_SEGUNDO_NUMERO;

DECLARE
NOTA INT:= &DIME_TU_NOTA;

BEGIN
IF NOTA>=9 THEN

    DBMS_OUTPUT.PUT_LINE( 'TIENE UN SOBRESALIENTE');
    ELSIF NOTA>=7 THEN
    DBMS_OUTPUT.PUT_LINE( 'TIENE UN NOTABLE');
    ELSIF NOTA>=6 THEN
     DBMS_OUTPUT.PUT_LINE( 'TIENE UN BIEN');
     ELSIF NOTA >=5 THEN
    DBMS_OUTPUT.PUT_LINE( 'TIENE UN APROBADO');
    ELSIF NOTA<5 THEN
    DBMS_OUTPUT.PUT_LINE( 'TIENE UN SUSPENSO');
    ELSE
    DBMS_OUTPUT.PUT_LINE("SU NUMERO ES ERRONEO ");
  
    END IF;
END;
/
UNDEFINE DIME_TU_NOTA;
DECLARE
NOTA INT:= &DIME_TU_NOTA;
BEGIN
WHEN NOTA>=9 THEN

    DBMS_OUTPUT.PUT_LINE( 'TIENE UN SOBRESALIENTE');
    WHEN NOTA>=7 THEN
    DBMS_OUTPUT.PUT_LINE( 'TIENE UN NOTABLE');
    WHEN NOTA>=6 THEN
     DBMS_OUTPUT.PUT_LINE( 'TIENE UN BIEN');
     WHEN NOTA >=5 THEN
    DBMS_OUTPUT.PUT_LINE( 'TIENE UN APROBADO');
    WHEN NOTA<5 THEN
    DBMS_OUTPUT.PUT_LINE( 'TIENE UN SUSPENSO');
    ELSE
    DBMS_OUTPUT.PUT_LINE("SU NUMERO ES ERRONEO ");
  
    END IF;
END;
/
UNDEFINE DIME_TU_NOTA;


DECLARE
NUMERO EMP.EMPNO%TYPE:= &DIME_UN_MUMERO;
NOMBRE EMP.ENAME%TYPE;
BEGIN
    SELECT ENAME INTO NOMBRE FROM EMP WHERE EMPNO =NUMERO;
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL EMPLEADO ES '|| NOMBRE);
END;
/
UNDEFINE DIME_UN_MUMERO;

DECLARE
NUMERO EMP.EMPNO%TYPE:= &DIME_UN_MUMERO;
NOMBRE EMP.ENAME%TYPE;
BEGIN
    SELECT ENAME INTO NOMBRE FROM EMP WHERE EMPNO =NUMERO;
    IF LENGTH(NOMBRE)>0 THEN
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL EMPLEADO ES '|| NOMBRE||'.');
    ELSE
    DBMS_OUTPUT.PUT_LINE('EL EMPLEADO NO EXISTE.');
    END IF;
END;
/
UNDEFINE DIME_UN_MUMERO;